/* Single caharacter lexemes */
#define LPAREN_TOK '('
#define RPAREN_TOK ')'
#define CURL_LPAREN_TOK '{'
#define CURL_RPAREN_TOK '}'
#define DEFINE_TOK '#'
#define EQ_TOK '='
#define GT_TOK '>'
#define LT_TOK '<'
#define MINUS_TOK '-'
#define PLUS_TOK '+'
#define MULT_TOK '*'
#define DIVIDE_TOK '/'
#define MOD_TOK '%'
#define XOR_TOK '^'
#define NOT_TOK '!'
#define AND_TOK '&'
#define OR_TOK '|'
#define SEMICOLON_TOK ';'
#define COMMA_TOK ','
/* Reserved words */
#define WHILE_TOK 256
#define FOR_TOK 257
#define IF_TOK 258
#define ELSE_TOK 259
#define COMPARE_TOK 260
#define GTEQ_TOK 261
#define LTEQ_TOK 262
#define NOT_EQ_TOK 263
#define BIT_AND_TOK 264
#define BIT_OR_TOK 265
#define PLUS_EQ_TOK 266
#define MINUS_EQ_TOK 267
#define MULT_EQ_TOK 268
#define DIVIDE_EQ_TOK 269
#define RIGHT_SHIFT_TOK 270
#define LEFT_SHIFT_TOK 271
#define MINUS_MINUS_TOK 272
#define PLUS_PLUS_TOK 273
#define MOD_EQ_TOK 274
/* Identifier, constants..*/
#define ID_TOK 350
#define INTCONST 351

#define ERROR_TOK 0